# Generated by Django 4.0 on 2021-12-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_field', models.CharField(max_length=50)),
            ],
        ),
    ]
